name: Playwright Tests

on:
    push:
        branches:
            - feature

    pull_request:
        branches:
            - main

    workflow_dispatch:
        inputs:
            target_env:
                description: select environment
                required: true
                type: choice
                default: dev
                options:
                    - dev
                    - st
                    - mo

jobs:
    test:
        runs-on: ubuntu-latest
        environment: ${{github.event.inputs.target_env || 'dev'}} 

        steps:

            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 24

            # - name: Install dependencies
            #   run: npm install

            # - name: Install playwright browsers
            #   run: npx playwright install

            - name: Docker build
              run: docker build -t playwright_tests_suite .

            # - name: Build and push
            #   uses: docker/build-push-action@v6

            - name: Run tests
              run: |
                docker run -rm \
                -v ${{github.workspace}}/playwright-report:/app/playwright-report \
                playwright_tests_suite

            - name: Upload report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: report
                path: playwright-report/
        

